apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskia-deployment
  labels:
    app: flaskia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskia
  template:
    metadata:
      labels:
        app: flaskia
    spec:
      containers:
      - name: flaskia
        image: baillyj/flaskia:0.0.1
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: flaskia-service
spec:
  type: NodePort
  selector:
    app: flaskia
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30080
      targetPort: 5000